server:
  port: 8888

spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: classpath:/config/
  profiles:
    active: native
